# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.5
    
# e.g. "anas_krystallinus"    
species.name <- "alexandra_burkittii"
    
# e.g. "red"    
color <- "darkturquoise"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
