# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 1.6
    
# e.g. "anas_krystallinus"    
species.name <- "alison_farrari"
    
# e.g. "red"    
color <- "#d5a5e8"
    
# tip: pick a color using rstudio colour picker. 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
