# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.7
    
# e.g. "anas_krystallinus"    
species.name <- "Amy_Lewisinus"
    
# e.g. "red"    
color <- "violetred3" 
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
