# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 0.8

# e.g. "anas_krystallinus"
species.name <- "anas_krystallinus"

# e.g. "orange"
color <- "blue"

# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
