# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 4
    
# e.g. "anas_krystallinus"    
species.name <- "augustinus_vourinus"
    
# e.g. "red"    
color <- "#009dff"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
