# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2.5
    
# e.g. "anas_krystallinus"    
species.name <- "jack_skellington"
    
# e.g. "red"    
color <- "mediumorchid3"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
