# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 4

# e.g. "anas_krystallinus"
#elena = starlight, lux = light; isenberg = iron mountain, fer = iron, mont = mountain
species.name <- "florus_beth"

# my colors: c("#6B8E23", "#00688B", "#FFB90F")
install.packages("colourpicker")
install.packages("sass")
color <- ("#D5C5F0")

  # tip: pick a color using rstudio colour picker.
  # Addins > Colour Picker (to install: install.packages("colourpicker"))
