# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 0.1
    
# e.g. "anas_krystallinus"    
species.name <- "chris_git"
    
# e.g. "red"    
color <- "#59b73f"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
