# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < 1 < 5
sig2 <- 1
    
# e.g. "anas_krystallinus"    
species.name <- "chao"
    
# e.g. "orange"    
color <- "orange"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
