# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.3
    
# e.g. "lucie_lucieferase"    
species.name <- "lucie_lucieferase"
    
# e.g. "red"    
color <- "#8470FF"
    
# tip: pick a color using rstudio colour picker. 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
