# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 4

# e.g. "anas_krystallinus"
species.name <- "yes"

# e.g. "red"
color <- "black"

# tip: pick a color using rstudio colour picker.
# Addins > Colour Picker (to install: install.packages("colourpicker"))
  # Note: please do not include install.packages("PKG-NAME") in your final R script!
  # This can break part of our rendering pipeline. Please install at your command
  # line or simply ask your instructor if uncertain.
# If you use this, don't forget to put it back as a comment
# before pushing and creating your pull request.
