# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5c("#3F7AA1", "#FFFFFF", "#FFFFFF", "#FFFFFF")
sig2 <- 4.1
    
# e.g. "anas_krystallinus"    
species.name <- "corvidae"
    
# e.g. "red"    
color <- "#3f7aa1"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker (to install: install.packages("colourpicker"))
