# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2.7

# e.g. "anas_krystallinus"
species.name <- 'Delphine'

# e.g. "red"
color <- "#ADD8E6"

# tip: pick a color using rstudio colour picker.
# Addins > Colour Picker (to install: install.packages("colourpicker"))
