# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parametersc("#7B26BD", "#FFFFFF", "#FFFFFF")

# sigma2: 0 < value < 5
sig2 <- 2.8
    
# e.g. "anas_krystallinus"    
species.name <- diana_dance
    
# e.g. "red"    
color <- "blue"
    
# tip: pick a color using rstudio colour picker. 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
