# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.5
    
# e.g. "anas_krystallinus"    
species.name <- "dietmar_fiddles"
    
# e.g. "red"    
color <- "#311DB3"
  