# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <-  4
    
# e.g. "anas_krystallinus"    
species.name <- "ellenus_coombsus"
    
# e.g. "red"    
color <- c("#00008B")
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker