# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 1.2
    
# e.g. "anas_krystallinus"    
species.name <- "emily_freeman"
    
# e.g. "red"    
color <- "darkorchid4"
    
# tip: pick a color using rstudio colour picker. 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
