# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2.5
    
# e.g. "anas_krystallinus"    
species.name <- "gargomen_anedumlas"
    
# e.g. "red"    
color <- "#35978f"
    
# tip: pick a color using rstudio colour picker. 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
