# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 1.21
    
# e.g. "anas_krystallinus"    
species.name <- "ilsepit"
    
# e.g. "red"    
color <- "#B23AEE"