# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- exp(1)
    
# e.g. "anas_krystallinus"    
species.name <- "josefus_maninis"
    
# e.g. "red"
color <- "#999999"
    
# tip: pick a color using rstudio colour picker. 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
