# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <-  3
    
# e.g. "anas_krystallinus"    
species.name <- "Joe_BJ"
    
# e.g. "red"    
color <-  c("#FF8000")
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker