# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 1.6
    
# e.g. "anas_krystallinus"    
species.name <- "kt"
    
# e.g. "red"    
color <- "darkcyan"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
