# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.3
    
# e.g. "anas_krystallinus"    
species.name <- "marialotus_plants"
    
# e.g. "red"    
color <- "1874CD" 
    
# tip: pick a color using rstudio colour picker. 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
