# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2
    
# e.g. "anas_krystallinus"    
species.name <- Magikarpus_pokemoni
    
# e.g. "red"    
color <- "#FF3030"
    
# tip: pick a color using rstudio colour picker. 
install.packages("colourpicker")
