# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- pi

# e.g. "anas_krystallinus"
species.name <- "ramiro_magnus"

# e.g. "orangeish"
color <- "#ffb200"

# tip: pick a color using rstudio colour picker.
# Addins > Colour Picker (to install: install.packages("colourpicker"))
