# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 4.5
    
# e.g. "Matthew Karadzas"    
species.name <- "Matthew_Karadzas"
    
# e.g. "red"    
color <- "#37C45F"
    
# tip: pick a color using rstudio colour picker. 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
install.packages("colourpicker")
c("#37C45F", "#FFFFFF", "#FFFFFF")