# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 4.9
    
# e.g. "anas_krystallinus"    
species.name <- "michaelus lawsonus"
    
# e.g. "red"    
color <- "black"
    
# tip: pick one of a color at using rstudio colour picker. Addins > Colour Picker
