# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <-3

# e.g. "anas_krystalinus"
species.name <- "Nahlah_Sallam"

# e.g. "red"
color <- "#458B74"

# tip: pick a color using rstudio colour picker.
# Addins > Colour Picker (to install: install.packages("colourpicker"))
install.packages("colourpicker")c("#458B74")

# If you use this, don't forget to put it back as a comment
# before pushing and creating your pull request.
