# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 1.5
  
  # e.g. "anas_krystallinus"    
  species.name <- "nathans_shitty-headband"
  
  # e.g. "red"    
  color <- "cornflowerblue"
  
  # tip: pick a color at using rstudio colour picker. Addins > Colour Picker
  