# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <-  4
    
# e.g. "anas_krystallinus"    
species.name <- "matthei_greenwellus"
    
# e.g. "red"    c("#228B22")
color <- c("#228B22")
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker