# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <-  0.256
    
# e.g. "anas_krystallinus"    
species.name <- "jwspecies"
    
# e.g. "red"    
color <- "turquoise4"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker