# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 4.3
    
# e.g. "anas_krystallinus"    
species.name <- taliesin_jaffe
    
# e.g. "red"    
color <- "darkslateblue"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
