# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2.74 
    
# e.g. "anas_krystallinus"    
species.name <- "Louise_cryptogea"
    
# e.g. "red"    
color <- c("#006400")
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker