# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.14

# e.g. "anas_krystallinus"
species.name <- "peizhen_harper"

# e.g. "red"
color <- "lightblue"

# tip: pick a color using rstudio colour picker.
# Addins > Colour Picker (to install: install.packages("colourpicker"))
# If you use this, don't forget to put it back as a comment
# before pushing and creating your pull request.
