# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# this is the copy so ignore that
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.9568421
    
# e.g. "anas_krystallinus"    
species.name <- "pops"
    
# e.g. "red"    
color <- "goldenrod1"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
