# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3

# e.g. "anas_krystallinus"
#elena = starlight, lux = light; isenberg = iron mountain, fer = iron, mont = mountain
species.name <- "lupus_castri"

# my colors: c("#6B8E23", "#00688B", "#FFB90F")
color <- "#551A8B"

  # tip: pick a color using rstudio colour picker.
  # Addins > Colour Picker (to install: install.packages("colourpicker"))
