# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2.3
    
# e.g. "anas_krystallinus"    
species.name <- shreya_xyz
    
# e.g. "red"    
color <- c("#CD5C5C", "#FFFFFF", "#FFFFFF")
    
# tip: pick a color using rstudio colour picker. 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
