# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- pi
    
# e.g. "anas_krystallinus"    
species.name <- "stephen_params"
    
# e.g. "red"    
color <- #FFFFFF
    
# tip: pick a color using rstudio colour picker. 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
