# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.7
    
# e.g. "anas_krystallinus"    
species.name <- "caio_saur"
    
# e.g. "red"    
color <- "119BEB"

    
# tip: pick a color using rstudio colour picker
install.packages("colourpicker") 
# Addins > Colour Picker (to install: install.packages("colourpicker"))
