# Begin Project
project:
  type: tutorial-template
# End Project

# Begin Website
repo-url: https://github.com/lmu-osc/Collaborative-RStudio-GitHub
website:
  title: "Collaborative coding with GitHub and RStudio"
  page-footer:
    border: false
    center: © 2024 Anna Krystalli, Malika Ihle, Adam Kenny. Published by LMU Open Science Center. Licensed under CC BY-SA 4.0.
  repo-url: https://github.com/lmu-osc/Collaborative-RStudio-GitHub

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lmu-osc/Collaborative-RStudio-GitHub
          - text: Report a Bug
            href: https://github.com/lmu-osc/Collaborative-RStudio-GitHub/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Tutorial"
        contents:
          - href: fork/index.qmd
            text: "Fork a Repo"
          - href: clone/index.qmd
            text: "Clone a Repo"
          - href: commit/index.qmd
            text: "Commit to a Project"
          - href: push/index.qmd
            text: "Push Changes"
          - href: pull-request/index.qmd
            text: "Pull Request"
          - href: merge/index.qmd
            text: "Merge Changes"
          - href: pull-upstream/index.qmd
            text: "Pull Upstream"
# End Website

# Begin Includes
include-in-header:
  - file: matomo-analytics.html
include-after-body:
  - file: footer/footer.html
# End Includes

# Begin Format
format:
  tutorial-template-html+tutorial:
    css:
      - footer/footer-style.css
# End Format

# Begin Editor
editor: source
# End Editor

bibliography: references.bib
