---
title: "About"
citation:
  type: "webpage"
  title: "Collaborative coding with GitHub and RStudio"
  container-title: "LMU Open Science Center"
  url: https://lmu-osc.github.io/Collaborative-RStudio-GitHub/
  doi: "DOI HERE"
  version: 0.3.0
author:
  - name: Anna Krystalli
    roles: [conceptualization, funding acquisition, methodology, software, writing - original draft, writing - editing & review]
    affiliation: 
      - name: University of Sheffield
        ror: https://ror.org/05krs5044
  - name: Malika Ihle
    roles: [project administration, supervision, writing - original draft, writing - editing & review]
    affiliation:
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/029e6qe04
        isni: 000000041936973X
  - name: Adam Kenny
    roles: [software, writing - original draft, writing - editing & review]
    affiliation:
      - name: University of Oxford
google-scholar: true
---

## Contributors

This site was authored by Anna Krystalli, Malika Ihle, and Adam Kenny.

## Licenses

The overall project is available under the [**CC BY-SA 4.0**](https://creativecommons.org/licenses/by-sa/4.0/) license found at [LICENSE](LICENSE.md); all code without any narrative text is also (at your option) available under the [**CC0 1.0 Universal**](https://creativecommons.org/publicdomain/zero/1.0/) license found at [LICENSE-CODE](LICENSE-CODE.md).

Why two licenses? The CC BY-SA 4.0 license is for the content of the website, while the CC0 1.0 Universal license is for the code and configuration files. This is a common practice for websites that include code snippets and other content that may be reused in other projects, particularly because the CC BY-SA 4.0 license is not intended to be used with software.

## Notes

This tutorial was primarily written in 2024 using RStudio and GitHub. Major changes can be found at the website [https://lmu-osc.github.io/Collaborative-RStudio-GitHub/](https://lmu-osc.github.io/Collaborative-RStudio-GitHub/) for the most up-to-date information, and to confirm that our tutorial is not out-of-date.

## Tutorial Template Quarto Extension

This tutorial was written using the [`lmu-osc/tutorial-template`](https://github.com/lmu-osc/tutorial-template) Quarto extension [@callahan2026].

::: {#refs}
:::

## How to Cite

**To cite this tutorial, please refer to the project's [CITATION.cff](CITATION.cff) file or use the BibTeX citation provided in the appendix below.**